version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ecommerce-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app              # Mount project folder
      - /app/node_modules   # Avoid overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fix file change detection inside Docker
